# .github/release.yml

changelog:
  exclude:
    labels:
      - 
    authors:
      - lukefretwell
  categories:
    - title: Breaking Changes 🛠
      labels:
        - 
        - 
    - title: Exciting New Features 🎉
      labels:
        - 
        - 
    - title: Other Changes
      labels:
        - "*"
